---
- hosts: localhost
  vars:
   vdom: "root"
  vars_prompt:
      - name: firewallip
        prompt: "Enter firewall IP"
        private: no
      - name: username
        prompt: "Enter your username"
        private: no
      - name: password
        prompt: "Enter your Password"
        
  tasks:
  - name: Genrate password
    shell: sudo /usr/local/src/PLAYBOOKS/scripts/getpass.py
    delegate_to: localhost

  - name: Genrate template
    shell: sudo  ansible-playbook /usr/local/src/PLAYBOOKS/scripts/csv_to_yaml.yaml
    delegate_to: localhost

  - name: Include yaml file created in above task
    include_vars: /usr/local/src/PLAYBOOKS/scripts/iterate_users.yml

  - name: Configure local users
    fortios_user_local:
      host:  "{{ firewallip }}"
      username: "{{ username }}"
      password: "{{ password }}"
      vdom:  "{{ vdom }}"
      ssl_verify: "False"
      https: "True"
      state: "present"
      user_local:
        name: "{{ item.name }}"
        passwd: "{{ item.password }}"
    with_items: "{{ user_details  }}"

  - name: Send Password
    shell: sudo /usr/local/src/PLAYBOOKS/scripts/send_vpn_mail.py "{{ item.usermail }}" "{{item.name}}" "{{item.password}}"
    with_items: "{{ user_details  }}"
    delegate_to: localhost

  - name: clear logs
    shell: sudo rm -vf /usr/local/src/PLAYBOOKS/logs/ansible.log
    delegate_to: localhost

  - name: clear template
    shell: sudo rm -vf /usr/local/src/PLAYBOOKS/scripts/iterate_users.yml
    delegate_to: localhost

  - name: Sending password file on email
    mail:
      host: my_organization.protection.outlook.com
      port: 25
      from: DC-Network-Ops@pubmatic.com
      to: tejas.mokashi@pubmatic.com
      subject: Ansible-password-file.
      body: PFA Password File
      attach:
      - /usr/local/src/PLAYBOOKS/scripts/output.txt

  - name: clear userdetails
    shell: sudo rm -vf /usr/local/src/PLAYBOOKS/scripts/output.txt
    delegate_to: localhost
